<?php

return array(
    array(
        "name" => "12 labels",
        "width" => 105,
        "height" => 48,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 4.5,
        "marginBottom" => 4.5,
        "aroundCount" => 6,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "12 labels",
        "width" => 70,
        "height" => 67.7,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 13.1,
        "marginBottom" => 13.1,
        "aroundCount" => 4,
        "acrossCount" => 3,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "14 labels",
        "width" => 105,
        "height" => 41,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 5,
        "marginBottom" => 5,
        "aroundCount" => 7,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "14 labels",
        "width" => 105,
        "height" => 42.4,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.1,
        "marginBottom" => 0.1,
        "aroundCount" => 7,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "14 labels",
        "width" => 105,
        "height" => 38,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 15.5,
        "marginBottom" => 15.5,
        "aroundCount" => 7,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "16 labels",
        "width" => 105,
        "height" => 35,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 8.5,
        "marginBottom" => 8.5,
        "aroundCount" => 8,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "16 labels",
        "width" => 105,
        "height" => 37,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.5,
        "marginBottom" => 0.5,
        "aroundCount" => 8,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "21 labels",
        "width" => 70,
        "height" => 42.41,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.1,
        "marginBottom" => 0.1,
        "aroundCount" => 7,
        "acrossCount" => 3,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "24 labels",
        "width" => 70,
        "height" => 37,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.5,
        "marginBottom" => 0.5,
        "aroundCount" => 8,
        "acrossCount" => 3,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "40 labels",
        "width" => 52.5,
        "height" => 29.6,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.5,
        "marginBottom" => 0.5,
        "aroundCount" => 10,
        "acrossCount" => 4,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "44 labels",
        "width" => 48.5,
        "height" => 25.4,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 8,
        "marginRight" => 8,
        "marginTop" => 8.8,
        "marginBottom" => 8.8,
        "aroundCount" => 11,
        "acrossCount" => 4,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "56 labels",
        "width" => 52.5,
        "height" => 21.2,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.1,
        "marginBottom" => 0.1,
        "aroundCount" => 14,
        "acrossCount" => 4,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "65 labels",
        "width" => 38.1,
        "height" => 21.2,
        "around" => 0,
        "across" => 2,
        "marginLeft" => 5.7,
        "marginRight" => 5.8,
        "marginTop" => 10.7,
        "marginBottom" => 10.7,
        "aroundCount" => 13,
        "acrossCount" => 5,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "120 labels",
        "width" => 22,
        "height" => 16,
        "around" => 2,
        "across" => 2,
        "marginLeft" => 10,
        "marginRight" => 10,
        "marginTop" => 14.5,
        "marginBottom" => 14.5,
        "aroundCount" => 15,
        "acrossCount" => 8,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "189 labels",
        "width" => 25.4,
        "height" => 10,
        "around" => 0,
        "across" => 2.5,
        "marginLeft" => 8.6,
        "marginRight" => 8.6,
        "marginTop" => 13.5,
        "marginBottom" => 13.5,
        "aroundCount" => 27,
        "acrossCount" => 7,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "230 labels",
        "width" => 14,
        "height" => 9,
        "around" => 3,
        "across" => 5,
        "marginLeft" => 12.5,
        "marginRight" => 12.5,
        "marginTop" => 12,
        "marginBottom" => 12,
        "aroundCount" => 23,
        "acrossCount" => 10,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "324 labels",
        "width" => 17,
        "height" => 6,
        "around" => 2,
        "across" => 3,
        "marginLeft" => 16.5,
        "marginRight" => 16.5,
        "marginTop" => 5.5,
        "marginBottom" => 5.5,
        "aroundCount" => 36,
        "acrossCount" => 9,
        "paperId" => 1,
        "default" => 0,
    ),
    array(
        "name" => "6 labels",
        "width" => 4.0000,
        "height" => 3.3300,
        "around" => 0.0000,
        "across" => 0.1870,
        "marginLeft" => 0.1560,
        "marginRight" => 0.1560,
        "marginTop" => 0.5050,
        "marginBottom" => 0.5050,
        "aroundCount" => 3,
        "acrossCount" => 2,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "8 labels",
        "width" => 3.3750,
        "height" => 2.3125,
        "around" => 0.1875,
        "across" => 0.3750,
        "marginLeft" => 0.6875,
        "marginRight" => 0.6875,
        "marginTop" => 0.5940,
        "marginBottom" => 0.5935,
        "aroundCount" => 4,
        "acrossCount" => 2,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "10 labels",
        "width" => 4.0000,
        "height" => 2.0000,
        "around" => 0.0000,
        "across" => 0.1400,
        "marginLeft" => 0.1800,
        "marginRight" => 0.1800,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 5,
        "acrossCount" => 2,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "10 labels",
        "width" => 3.0000,
        "height" => 2.0000,
        "around" => 0.1250,
        "across" => 0.1250,
        "marginLeft" => 1.1875,
        "marginRight" => 1.1875,
        "marginTop" => 0.2500,
        "marginBottom" => 0.2500,
        "aroundCount" => 5,
        "acrossCount" => 2,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "12 labels",
        "width" => 2.1250,
        "height" => 2.1250,
        "around" => 0.1500,
        "across" => 0.1500,
        "marginLeft" => 0.9125,
        "marginRight" => 0.9125,
        "marginTop" => 1.0250,
        "marginBottom" => 1.0250,
        "aroundCount" => 4,
        "acrossCount" => 3,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "18 labels",
        "width" => 2.5000,
        "height" => 1.5625,
        "around" => 0.1250,
        "across" => 0.1250,
        "marginLeft" => 0.3750,
        "marginRight" => 0.3750,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 6,
        "acrossCount" => 3,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "20 labels",
        "width" => 2.0000,
        "height" => 2.0000,
        "around" => 0.1250,
        "across" => 0.0000,
        "marginLeft" => 0.2500,
        "marginRight" => 0.2500,
        "marginTop" => 0.2500,
        "marginBottom" => 0.2500,
        "aroundCount" => 5,
        "acrossCount" => 4,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "20 labels",
        "width" => 4.0000,
        "height" => 1.0000,
        "around" => 0.0100,
        "across" => 0.1563,
        "marginLeft" => 0.1700,
        "marginRight" => 0.1700,
        "marginTop" => 0.4400,
        "marginBottom" => 0.4400,
        "aroundCount" => 10,
        "acrossCount" => 2,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "30 labels",
        "width" => 2.6250,
        "height" => 1.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 0.3125,
        "marginRight" => 0.3125,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 10,
        "acrossCount" => 3,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "30 labels",
        "width" => 2.6250,
        "height" => 1.0000,
        "around" => 0.0000,
        "across" => 0.1400,
        "marginLeft" => 0.1260,
        "marginRight" => 0.2190,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 10,
        "acrossCount" => 3,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "32 labels",
        "width" => 1.7500,
        "height" => 1.2500,
        "around" => 0.0000,
        "across" => 0.1900,
        "marginLeft" => 0.4650,
        "marginRight" => 0.4650,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 8,
        "acrossCount" => 4,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "40 labels",
        "width" => 2.0000,
        "height" => 1.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 0.2500,
        "marginRight" => 0.2500,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 10,
        "acrossCount" => 4,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "50 labels",
        "width" => 1.5000,
        "height" => 1.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 0.5000,
        "marginRight" => 0.5000,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 10,
        "acrossCount" => 5,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "60 labels",
        "width" => 1.7500,
        "height" => 0.6660,
        "around" => 0.0000,
        "across" => 0.2725,
        "marginLeft" => 0.3750,
        "marginRight" => 0.3075,
        "marginTop" => 0.5050,
        "marginBottom" => 0.5050,
        "aroundCount" => 15,
        "acrossCount" => 4,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "100 labels",
        "width" => 1.5000,
        "height" => 0.5000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 0.5000,
        "marginRight" => 0.5000,
        "marginTop" => 0.5000,
        "marginBottom" => 0.5000,
        "aroundCount" => 20,
        "acrossCount" => 5,
        "paperId" => 2,
        "default" => 0,
    ),
    array(
        "name" => "10 labels",
        "width" => 105.0000,
        "height" => 48.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 2.5000,
        "marginRight" => 2.5000,
        "marginTop" => 20.0000,
        "marginBottom" => 20.0000,
        "aroundCount" => 5,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "12 labels",
        "width" => 70.0000,
        "height" => 67.7000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 2.5000,
        "marginRight" => 2.5000,
        "marginTop" => 4.6000,
        "marginBottom" => 4.6000,
        "aroundCount" => 4,
        "acrossCount" => 3,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "14 labels",
        "width" => 105.3900,
        "height" => 40.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 1.1100,
        "marginRight" => 1.1100,
        "marginTop" => 0.0000,
        "marginBottom" => 0.0000,
        "aroundCount" => 7,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "14 labels",
        "width" => 105.0000,
        "height" => 42.0000,
        "around" => 2.0000,
        "across" => 2.0000,
        "marginLeft" => 1.5000,
        "marginRight" => 1.5000,
        "marginTop" => 9.0000,
        "marginBottom" => 9.0000,
        "aroundCount" => 6,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "16 labels",
        "width" => 105.0000,
        "height" => 35.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 1.5000,
        "marginRight" => 1.5000,
        "marginTop" => 0.0000,
        "marginBottom" => 0.0000,
        "aroundCount" => 8,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "16 labels ",
        "width" => 105.0000,
        "height" => 32.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 1.5000,
        "marginRight" => 1.5000,
        "marginTop" => 12.0000,
        "marginBottom" => 12.0000,
        "aroundCount" => 8,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "18 labels",
        "width" => 104.0000,
        "height" => 30.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 2.5000,
        "marginRight" => 2.5000,
        "marginTop" => 5.0000,
        "marginBottom" => 5.0000,
        "aroundCount" => 9,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "18 labels",
        "width" => 105.0000,
        "height" => 30.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 2.5000,
        "marginRight" => 2.5000,
        "marginTop" => 5.0000,
        "marginBottom" => 5.0000,
        "aroundCount" => 9,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "21 labels",
        "width" => 68.0000,
        "height" => 39.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 3.5000,
        "marginRight" => 3.5000,
        "marginTop" => 3.5000,
        "marginBottom" => 3.5000,
        "aroundCount" => 7,
        "acrossCount" => 3,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "21 labels",
        "width" => 70.0000,
        "height" => 37.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 2.5000,
        "marginRight" => 2.5000,
        "marginTop" => 10.5000,
        "marginBottom" => 10.5000,
        "aroundCount" => 7,
        "acrossCount" => 3,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "22 labels",
        "width" => 105.0000,
        "height" => 22.0000,
        "around" => 2.0000,
        "across" => 2.0000,
        "marginLeft" => 1.5000,
        "marginRight" => 1.5000,
        "marginTop" => 9.0000,
        "marginBottom" => 9.0000,
        "aroundCount" => 11,
        "acrossCount" => 2,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "24 labels",
        "width" => 68.5000,
        "height" => 34.5000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 2.7500,
        "marginRight" => 2.7500,
        "marginTop" => 2.0000,
        "marginBottom" => 2.0000,
        "aroundCount" => 8,
        "acrossCount" => 3,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "27 labels",
        "width" => 69.0000,
        "height" => 30.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 2.0000,
        "marginRight" => 2.0000,
        "marginTop" => 5.0000,
        "marginBottom" => 5.0000,
        "aroundCount" => 9,
        "acrossCount" => 3,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "30 labels",
        "width" => 69.0000,
        "height" => 28.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 2.0000,
        "marginRight" => 2.0000,
        "marginTop" => 0.0000,
        "marginBottom" => 0.0000,
        "aroundCount" => 10,
        "acrossCount" => 3,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "40 labels",
        "width" => 40.0000,
        "height" => 39.0000,
        "around" => 0.0000,
        "across" => 2.0000,
        "marginLeft" => 3.5000,
        "marginRight" => 3.5000,
        "marginTop" => 3.5000,
        "marginBottom" => 3.5000,
        "aroundCount" => 7,
        "acrossCount" => 5,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "50 labels",
        "width" => 38.0000,
        "height" => 25.0000,
        "around" => 2.0000,
        "across" => 2.0000,
        "marginLeft" => 8.5000,
        "marginRight" => 8.5000,
        "marginTop" => 6.0000,
        "marginBottom" => 6.0000,
        "aroundCount" => 10,
        "acrossCount" => 5,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "55 labels",
        "width" => 42.0000,
        "height" => 25.0000,
        "around" => 0.0000,
        "across" => 0.0000,
        "marginLeft" => 2.5000,
        "marginRight" => 2.5000,
        "marginTop" => 2.5000,
        "marginBottom" => 2.5000,
        "aroundCount" => 11,
        "acrossCount" => 5,
        "paperId" => 3,
        "default" => 0,
    ),
    array(
        "name" => "roll",
        "width" => 0,
        "height" => 0,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0,
        "marginBottom" => 0,
        "aroundCount" => 1,
        "acrossCount" => 1,
        "paperId" => 4,
        "default" => 1,
    ),
    array(
        "name" => "roll",
        "width" => 0,
        "height" => 0,
        "around" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0,
        "marginBottom" => 0,
        "aroundCount" => 1,
        "acrossCount" => 1,
        "paperId" => 5,
        "default" => 1,
    ),
);
