<?php

return array(
    array(
        'id' => 1,
        'name' => 'A4',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol_id' => 1,
        'is_editable' => 1,
    ),
    array(
        'id' => 2,
        'name' => 'Letter',
        'width' => 8.5,
        'height' => 11,
        'default' => 1,
        'uol_id' => 2,
        'is_editable' => 1,
    ),
    array(
        'id' => 3,
        'name' => 'P4',
        'width' => 215,
        'height' => 280,
        'default' => 1,
        'uol_id' => 1,
        'is_editable' => 1,
    ),
    array(
        'id' => 4,
        'name' => 'Label printer',
        'width' => 70,
        'height' => 44,
        'default' => 1,
        'uol_id' => 1,
        'is_roll' => 1,
        'is_editable' => 1,
        'landscape' => 1,
    ),
    array(
        'id' => 5,
        'name' => 'Label printer',
        'width' => 2.7,
        'height' => 1.7,
        'default' => 1,
        'uol_id' => 2,
        'is_roll' => 1,
        'is_editable' => 1,
        'landscape' => 1,
    ),
    array(
        'id' => 6,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol_id' => 1,
        'is_editable' => 0,
    ),
    array(
        'id' => 7,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol_id' => 1,
        'is_editable' => 0,
    ),
    array(
        'id' => 8,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol_id' => 1,
        'is_editable' => 0,
    ),
    array(
        'id' => 9,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol_id' => 1,
        'is_editable' => 0,
    ),
);
