<?php

return array(
    array(
        'id' => 1,
        'name' => 'CODE128',
        'shortcode' => '[barcode id=XXXX shortcode=1]',
        'matching' => '{"template":"1","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"_sku","type":"custom"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"C128","withVariations":false}',
        'type' => 'product',
        'is_default' => 1,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-1',
    ),
    array(
        'id' => 2,
        'name' => 'CODE128',
        'shortcode' => '[barcode id=XXXX shortcode=2]',
        'matching' => '{"template":"1","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"ID","type":"orderStandart"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"C128","withVariations":false}',
        'type' => 'order',
        'is_default' => 1,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-1',
    ),
    array(
        'id' => 3,
        'name' => 'CODE39',
        'shortcode' => '[barcode id=XXXX shortcode=3]',
        'matching' => '{"template":"1","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"_sku","type":"custom"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"C39","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-2',
    ),
    array(
        'id' => 4,
        'name' => 'QRCode',
        'shortcode' => '[barcode id=XXXX shortcode=4]',
        'matching' => '{"template":"5","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"post_title","type":"standart"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"QRCODE","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-3',
    ),
    array(
        'id' => 5,
        'name' => 'DataMatrix',
        'shortcode' => '[barcode id=XXXX shortcode=5]',
        'matching' => '{"template":"5","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"post_title","type":"standart"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"DATAMATRIX","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-4',
    ),
    array(
        'id' => 6,
        'name' => 'EAN 13',
        'shortcode' => '[barcode id=XXXX shortcode=6]',
        'matching' => '{"template":"9","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"post_title","type":"standart"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"EAN13","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-5',
    ),
    array(
        'id' => 7,
        'name' => 'EAN 8',
        'shortcode' => '[barcode id=XXXX shortcode=7]',
        'matching' => '{"template":"9","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"post_title","type":"standart"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"EAN8","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-6',
    ),
    array(
        'id' => 8,
        'name' => 'UPC-A',
        'shortcode' => '[barcode id=XXXX shortcode=8]',
        'matching' => '{"template":"9","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"post_title","type":"standart"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"UPCA","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-7',
    ),
    array(
        'id' => 9,
        'name' => 'UPC-E',
        'shortcode' => '[barcode id=XXXX shortcode=9]',
        'matching' => '{"template":"9","lineBarcode":{"value":"_sku","type":"custom"},"fieldLine1":{"value":"post_title","type":"standart"},"fieldLine2":{"value":"_price","type":"custom"},"fieldLine3":{"value":"_sku","type":"custom"},"fieldLine4":{"value":"wc_category","type":"wc_category"},"format":"UPCE","withVariations":false}',
        'type' => 'product',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'product-8',
    ),
    array(
        'id' => 10,
        'name' => 'CODE39',
        'shortcode' => '[barcode id=XXXX shortcode=10]',
        'matching' => '{"template":"1","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"C39","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-2',
    ),
    array(
        'id' => 11,
        'name' => 'QRCode',
        'shortcode' => '[barcode id=XXXX shortcode=11]',
        'matching' => '{"template":"5","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"QRCODE","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-3',
    ),
    array(
        'id' => 12,
        'name' => 'DataMatrix',
        'shortcode' => '[barcode id=XXXX shortcode=12]',
        'matching' => '{"template":"5","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"DATAMATRIX","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-4',
    ),
    array(
        'id' => 13,
        'name' => 'EAN 13',
        'shortcode' => '[barcode id=XXXX shortcode=13]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"EAN13","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-5',
    ),
    array(
        'id' => 14,
        'name' => 'EAN 8',
        'shortcode' => '[barcode id=XXXX shortcode=14]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"EAN8","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-6',
    ),
    array(
        'id' => 15,
        'name' => 'UPC-A',
        'shortcode' => '[barcode id=XXXX shortcode=15]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"UPCA","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-7',
    ),
    array(
        'id' => 16,
        'name' => 'UPC-E',
        'shortcode' => '[barcode id=XXXX shortcode=16]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"UPCE","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-8',
    ),
    array(
        'id' => 25,
        'name' => 'ZATCA',
        'shortcode' => '[barcode id=XXXX shortcode=25]',
        'matching' => '{"template":"10","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"","type":"static"},"fieldLine4":{"value":"","type":"static"},"format":"QRCODE","withVariations":false}',
        'type' => 'order',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'order-9',
    ),
    array(
        'id' => 17,
        'name' => 'CODE128',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"1","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"ID","type":"orderStandart"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"C128","withVariations":false}',
        'type' => 'custom',
        'is_default' => 1,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-1',
    ),
    array(
        'id' => 18,
        'name' => 'CODE39',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"1","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"C39","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-2',
    ),
    array(
        'id' => 19,
        'name' => 'QRCode',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"5","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"QRCODE","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-3',
    ),
    array(
        'id' => 20,
        'name' => 'DataMatrix',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"5","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"DATAMATRIX","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-4',
    ),
    array(
        'id' => 21,
        'name' => 'EAN 13',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"EAN13","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-5',
    ),
    array(
        'id' => 22,
        'name' => 'EAN 8',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"EAN8","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-6',
    ),
    array(
        'id' => 23,
        'name' => 'UPC-A',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"UPCA","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-7',
    ),
    array(
        'id' => 24,
        'name' => 'UPC-E',
        'shortcode' => '[barcode code=XXXX shortcode=SHORTCODE_ID]',
        'matching' => '{"template":"9","lineBarcode":{"value":"ID","type":"orderStandart"},"fieldLine1":{"value":"","type":"static"},"fieldLine2":{"value":"","type":"static"},"fieldLine3":{"value":"ID","type":"orderStandart"},"fieldLine4":{"value":"","type":"static"},"format":"UPCE","withVariations":false}',
        'type' => 'custom',
        'is_default' => 0,
        'is_edit' => 1,
        'is_base' => 1,
        'slug' => 'custom-8',
    ),
);
