<?php
/**
 * View for the Add PO Delivery modal's JS template
 *
 * @since 0.9.0
 *
 * @var \AtumPO\Models\POExtended            $po
 * @var \AtumPO\Deliveries\Models\Delivery[] $deliveries
 */

defined( 'ABSPATH' ) || die;

use Atum\Inc\Helpers as AtumHelpers;

?>
<script type="text/template" id="add-delivery-modal">
	<div class="atum-modal-content">

		<div class="note">
			<?php esc_html_e( 'Add a delivery to this purchase order.', ATUM_PO_TEXT_DOMAIN ) ?><br>
		</div>

		<hr>

		<div class="po-modal__details">
			<h4><?php esc_html_e( 'Delivery Details', ATUM_PO_TEXT_DOMAIN ); ?></h4>

			<div class="po-modal__details-field full-width">
				<label for=""><?php esc_html_e( 'Delivery Name', ATUM_PO_TEXT_DOMAIN ); ?></label>
				<input type="text" name="delivery_name" placeholder="<?php esc_attr_e( 'Will be autogenerated if empty', ATUM_PO_TEXT_DOMAIN ); ?>">
			</div>

			<div class="po-modal__details-field pr">
				<label for=""><?php esc_html_e( 'Date', ATUM_PO_TEXT_DOMAIN ); ?></label>

				<span class="date-field with-icon">
					<input type="text" name="delivery_date" class="atum-datepicker"
						placeholder="<?php esc_attr_e( 'Will be current date if empty', ATUM_PO_TEXT_DOMAIN ); ?>"
						data-date-format="YYYY-MM-DD HH:mm" data-min-date="false"
					>
				</span>
			</div>

			<div class="po-modal__details-field">
				<label for=""><?php esc_html_e( 'Document Number', ATUM_PO_TEXT_DOMAIN ); ?></label>
				<input type="text" name="delivery_doc_number" placeholder="<?php esc_attr_e( 'Add the document number', ATUM_PO_TEXT_DOMAIN ); ?>">
			</div>

		</div>

		<hr>

		<div class="po-modal__search">

			<h4><?php esc_html_e( 'Delivery Items', ATUM_PO_TEXT_DOMAIN ); ?></h4>

			<?php
			$po_items    = $po->get_items();
			$shown_items = 0;
			?>

			<?php if ( empty( $po_items ) ) : ?>

				<div class="alert alert-primary">
					<i class="atum-icon atmi-question-circle"></i>
					<?php esc_html_e( 'Please, first add items to the PO and save', ATUM_PO_TEXT_DOMAIN ); ?>
				</div>

			<?php else : ?>

				<div class="po-modal__search-input">
					<input type="text" id="search-delivery-products" placeholder="<?php esc_attr_e( 'Search for products&hellip;', ATUM_PO_TEXT_DOMAIN ); ?>"/>
				</div>

				<form id="add-delivery-items-form">
					<table class="atum-items-table po-modal__items">
						<thead>
						<tr>
							<th colspan="2"><?php esc_attr_e( 'Item', ATUM_PO_TEXT_DOMAIN ); ?></th>
							<th class="center"><?php esc_attr_e( 'Expected', ATUM_PO_TEXT_DOMAIN ); ?></th>
							<th class="center"><?php esc_attr_e( 'Already In', ATUM_PO_TEXT_DOMAIN ); ?></th>
							<th class="center"><?php esc_attr_e( 'Delivered', ATUM_PO_TEXT_DOMAIN ); ?></th>
						</tr>
						</thead>
						<tbody>
							<?php foreach ( $po_items as $po_item ) :

								// Allow bypassing an item externally.
								if ( ! apply_filters( 'atum/purchase_orders_pro/delivery_modal/show_item', TRUE, $po_item ) ) :
									continue;
								endif;

								$po_item_id = $po_item->get_id();
								$product_id = $po_item->get_variation_id() ?: $po_item->get_product_id();
								$product    = AtumHelpers::get_atum_product( $po_item->get_product() );
								$expected   = $po_item->get_quantity();
								$already_in = 0;

								foreach ( $deliveries as $delivery ) :

									$delivery_items = $delivery->get_items();

									foreach ( $delivery_items as $delivery_item ) :

										/**
										 * Variable definition
										 *
										 * @var \AtumPO\Deliveries\Items\DeliveryItemProduct $delivery_item
										 */
										if ( $delivery_item->get_po_item_id() === $po_item_id ) :
											$already_in += $delivery_item->get_quantity();
											break;
										endif;

									endforeach;

								endforeach;

								$pending = $expected - $already_in;

								if ( $pending <= 0 ) :
									continue; // This item is fully delivered, so just don't show it.
								endif;

								$shown_items++;
								?>
								<tr class="<?php echo esc_attr( apply_filters( 'atum/purchase_orders_pro/delivery_item_css_class', 'delivery-item', $po_item, $product ) ) ?>"
									data-product_id="<?php echo esc_attr( $product_id ) ?>" data-item_id="<?php echo esc_attr( $po_item_id ) ?>"
								>
									<td class="thumb">
										<div class="atum-order-item-thumbnail">
											<?php $thumbnail = $product instanceof \WC_Product ? $product->get_image( [ 40, 40 ], array( 'title' => '' ), FALSE ) : ''; ?>
											<?php echo wp_kses_post( $thumbnail ) ?>
										</div>
									</td>
									<?php
									$item_class = '';
									$item_title = '';
									if ( ! $product instanceof \WC_Product ) {
										$item_class = ' deleted';
										$item_title = __( 'This product does not exist', ATUM_PO_TEXT_DOMAIN );
									}
									?>
									<td class="name<?php echo esc_attr( $item_class ); ?>">
										<div class="product-name" title="<?php echo esc_attr( $item_title ); ?>">
											<?php echo esc_html( $product instanceof \WC_Product ? $product->get_name() : $po_item->get_name() ) ?>
										</div>

										<?php if ( $product instanceof \WC_Product ) : ?>
										<div class="item-meta">

											<?php $sku = $product->get_sku() ?>

											<?php if ( $sku ) : ?>
												<div>
													<?php /* translators: the product SKU */
													printf( esc_html__( 'SKU: %s', ATUM_PO_TEXT_DOMAIN ), $sku ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
												</div>
											<?php endif; ?>

											<?php $supplier_sku = $product->get_supplier_sku() ?>

											<?php if ( $supplier_sku ) : ?>
												<div>
													<?php /* translators: the sipplier's SKU */
													printf( esc_html__( 'Supplier SKU: %s', ATUM_PO_TEXT_DOMAIN ), $supplier_sku ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
												</div>
											<?php endif; ?>

										</div>
										<?php endif; ?>
									</td>
									<td class="expected center">
										<?php echo esc_html( $expected ) ?>
									</td>
									<td class="already-in center">
										<?php echo esc_html( $already_in ) ?>
									</td>
									<td class="qty center">
										<?php if ( $product instanceof \WC_Product ) : ?>
										<input type="number" name="delivery_qty" data-id="<?php echo esc_attr( $po_item_id ) ?>"
											value="0" min="0" onfocus="this.select();"
											max="<?php echo esc_attr( $pending ) ?>" step="any"
										>
										<?php
										else :
											esc_attr_e( 'N/A', ATUM_PO_TEXT_DOMAIN );
										endif;
										?>
									</td>
								</tr>

								<?php do_action( 'atum/purchase_orders_pro/after_add_delivery_modal_item', $po_item, $product ) ?>

							<?php endforeach; ?>

							<?php if ( ! $shown_items ) : ?>
								<tr>
									<td colspan="5">
										<div class="alert alert-primary">
											<i class="atum-icon atmi-question-circle"></i>
											<?php esc_html_e( 'All the items have been already delivered', ATUM_PO_TEXT_DOMAIN ); ?>
										</div>
									</td>
								</tr>
							<?php endif; ?>
						</tbody>
					</table>
				</form>

			<?php endif; ?>
		</div>

		<div class="po-modal__total">
			<strong><?php esc_html_e( 'Total items:', ATUM_PO_TEXT_DOMAIN ); ?> <span class="total-items"><?php echo esc_html( $shown_items ) ?></span></strong>
		</div>
	</div>
</script>
