<?php

/**
 * This API allows you to create your own "shortcodes" which you can add to label templates
 * and they will be replaced with values you fetch in api.php
 * Follow the documentation here: https://www.ukrsolution.com/Wordpress/Print-Barcode-Labels-for-WooCommerce-Products#details
 */

/********************************
 * Add custom shortcodes hooks
 ********************************/

/********** Variant I (using hooks wrapper) ********************/
// Check for function existence
if (function_exists('uswbg_add_custom_shortcode')) {
    // Creation of the [random-number] shortcode
    uswbg_add_custom_shortcode('random-number', function ($value, $shortcode, $item, $field) {
        return rand(1, 100);
    });
}

/********** Variant II (outdated) ********/

/**
 * This hook allows to add any amount of custom shortcodes and use third party data for them.
 *
 * @param $item
 * @param $settings
 *
 * @return mixed
 */
function barcodes_products_after_hook($item, $settings)
{
    // Store here any values from third party data plugins/storage
    $productSize = "XXL";
    $productColor = "Green";

    // Came up with a shorcode you like and specify data for it
    $item["replacements"]['[productSize]'] = $productSize;
    $item["replacements"]['[productColor]'] = $productColor;

    // WooCommerce installed ? Barcode image has been generated by core ?
    if (is_plugin_active('woocommerce/woocommerce.php') === false || empty($item["image"]) === true) {
        // No, If you don't use woocommerce you will need to generate barcode image by yourself.

        // Store barcode image data here & generate image
        $imageCode = "1234567890";
        $item["image"] = UkrSolution\ProductLabelsPrinting\Generators\BarcodeImage::createXML($imageCode, $settings['format']);
    }

    return $item;
}

add_filter('barcodes_products_after_hook', 'barcodes_products_after_hook', 10, 3);


/*******************************************
 * Add custom sort method for labels hook
 *******************************************/

// Check for function existence
if (!function_exists('barcodes_products_sort_items_hook')) {
    /**
     * This hook allows applying custom sorting for label items.
     *
     * @param $items
     *
     * @return void
     */
    function barcodes_products_sort_items_hook($items)
    {
        // Example. Sort items by name.
        usort($items, function ($a, $b) {
            return strcmp($a->post_title, $b->post_title);
        });

        return $items;
    }
}

add_filter('barcodes_products_sort_items_hook', 'barcodes_products_sort_items_hook', 10, 3);
