<?php
/**
 * File: /wp-content/plugins/aaa-order-workflow/includes/productsearch/hooks/class-aaa-oc-productsearch-search-hooks.php
 * Purpose: Hook standard WooCommerce searches; resolve to product IDs from the
 *          index table and hand control back to WooCommerce. This class
 *          implements pre_get_posts and the WC datastore filter used in
 *          version 1.1.0 of the upstream plugin.
 *
 * Version: 1.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class AAA_OC_ProductSearch_Search_Hooks {
    /**
     * Initialise hooks. Call this once plugins are loaded. The loader
     * handles this automatically.
     */
    public static function init() {
        add_action( 'pre_get_posts', [ __CLASS__, 'pre_get_posts' ], 99 );
        add_filter( 'woocommerce_product_data_store_cpt_get_products_query', [ __CLASS__, 'wc_datastore' ], 99, 2 );
    }
    /**
     * Intercept the main query when it is a search and replace the
     * product results with those returned from the index. If no results
     * are found we let WordPress handle the search normally.
     *
     * @param WP_Query $q The query instance (passed by reference).
     */
    public static function pre_get_posts( $q ) {
        // Only adjust front‑end main queries.
        if ( is_admin() || ! $q->is_main_query() ) {
            return;
        }
        $s = (string) $q->get( 's' );
        if ( '' === $s ) {
            return;
        }
        // Resolve via ProductSearch index first.
        $ids = AAA_OC_ProductSearch_Helpers::search_index( $s );
        if ( empty( $ids ) ) {
            // Let WordPress do its normal search when our index has nothing.
            return;
        }
        // Apply redirect rule: only if all results share the same brand/category.
        AAA_OC_ProductSearch_Helpers::maybe_redirect_by_results( $s, $ids );
        // No redirect → constrain query to our product IDs.
        $q->set( 'post_type', [ 'product' ] );
        $q->set( 'post__in', $ids );
        $q->set( 'orderby', 'post__in' );
        // Avoid WP's broad text search after resolving IDs.
        $q->set( 's', '' );
    }
    /**
     * Intercept the WooCommerce datastore search. This ensures that API
     * requests and other programmatic queries also use the index. The
     * behaviour mirrors pre_get_posts() but operates on raw WC args.
     *
     * @param array $wp_args The WP query args generated by the WC store.
     * @param array $wc_query The original WC query args.
     * @return array Modified arguments including post__in where appropriate.
     */
    public static function wc_datastore( $wp_args, $wc_query ) {
        $s = $wp_args['s'] ?? ( $wp_args['search'] ?? '' );
        if ( ! $s ) {
            return $wp_args;
        }
        // Only adjust frontend/product contexts; avoid admin screens.
        if ( is_admin() ) {
            return $wp_args;
        }
        $ids = AAA_OC_ProductSearch_Helpers::search_index( $s );
        if ( empty( $ids ) ) {
            return $wp_args;
        }
        AAA_OC_ProductSearch_Helpers::maybe_redirect_by_results( $s, $ids );
        $wp_args['post__in'] = $ids;
        $wp_args['orderby']  = 'post__in';
        unset( $wp_args['s'], $wp_args['search'] );
        return $wp_args;
    }
}