<?php
/**
 * Plugin Name: AAA Account Portal
 * Description: Provides a unified login and lost‑password portal via shortcode with AJAX. Supports brand colours and registration URL configuration via a settings page. Designed for multisite installations with front‑end use in banners, modals or sidebars.
 * Version: 1.2.7
 * Author: Generated by AI
 *
 * This plugin follows a wide‑and‑thin architecture. The core loader pulls in
 * lightweight classes for assets, AJAX handlers, shortcode rendering and
 * settings. Each class lives in its own file and stays under 150 lines.
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Define a constant used throughout the plugin for internal checks.
if ( ! defined( 'AAA_ACP_VERSION' ) ) {
    define( 'AAA_ACP_VERSION', '1.2.7' );
}

// Require our class files. Each class handles a distinct concern.
require_once __DIR__ . '/includes/class-aaa-acp-assets.php';
require_once __DIR__ . '/includes/class-aaa-acp-ajax.php';
require_once __DIR__ . '/includes/class-aaa-acp-shortcode.php';
require_once __DIR__ . '/includes/class-aaa-acp-admin.php';

/**
 * Initialise all modules.
 */
function aaa_acp_init() {
    // Initialise asset loading (styles/scripts).
    AAA_ACP_Assets::init();
    // Register AJAX endpoints.
    AAA_ACP_Ajax::init();
    // Register the shortcode.
    AAA_ACP_Shortcode::init();
    // Register admin page and settings.
    AAA_ACP_Admin::init();
}
add_action( 'plugins_loaded', 'aaa_acp_init' );

/**
 * Add a quick link to the plugin settings from the plugins list table.
 *
 * @param array $links Existing action links.
 * @return array Modified action links.
 */
function aaa_acp_action_links( $links ) {
    $url = admin_url( 'options-general.php?page=aaa-acp-settings' );
    $links = (array) $links;
    array_unshift( $links, '<a href="' . esc_url( $url ) . '">Settings</a>' );
    return $links;
}
add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), 'aaa_acp_action_links' );