<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Kestrel\\Account_Funds\\Scoped\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Kestrel\\Account_Funds\\Scoped\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Kestrel\\Account_Funds\\Scoped\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'Kestrel\\Account_Funds\\Scoped\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Kestrel\\Account_Funds\\Scoped\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Kestrel\\Account_Funds\\Scoped\\Kestrel\\Fenix\\' => array($vendorDir . '/kestrelwp/fenix/src'),
    'Kestrel\\Account_Funds\\Scoped\\Doctrine\\Deprecations\\' => array($vendorDir . '/doctrine/deprecations/src'),
    'Kestrel\\Account_Funds\\Scoped\\Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib/Doctrine/Common/Collections'),
    'Kestrel\\Account_Funds\\Scoped\\CommerceGuys\\Addressing\\' => array($vendorDir . '/commerceguys/addressing/src'),
    'Kestrel\\Account_Funds\\Scoped\\Carbon\\Doctrine\\' => array($vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'),
    'Kestrel\\Account_Funds\\Scoped\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
);
